IBX-7792: The modal was adapted to the new schema, jQuery dependencies were removed
ibexa/automated-translation pull request #9
Opened 2024-02-19 14:33 UTC by mateuszdebinski

Jira: https://issues.ibexa.co/browse/IBX-7792

2024-02-28 13:32 UTC, GrabowskiM requested changes

2024-02-28 13:32 UTC, GrabowskiM commented on src/bundle/Resources/public/admin/js/ibexa-automated-translation.js
> +        const target = event.target;
```suggestion
    const toggleClass = ({ target }) => {
```
or 
```suggestion
    const toggleClass = (event) => {
        const { target } = event;
```

2024-02-28 13:32 UTC, GrabowskiM commented on src/bundle/Resources/public/admin/js/ibexa-automated-translation.js
> +        const input = target.querySelector('input[type="checkbox"]');
Are there any ibexa classes on this input? If yes, then it probably should be sth like (at least that's class that SHOULD be on checkbox input ;) )
```suggestion
        const input = target.querySelector('.ibexa-input--checkbox');
```

2024-02-28 13:32 UTC, GrabowskiM commented on src/bundle/Resources/public/admin/js/ibexa-automated-translation.js
> +            targetLang.indexOf(targetLang, languagesMapping[serviceAlias]) !== -1;
```suggestion
        const serviceLang = languagesMapping[serviceAlias];
        const translationAvailable = (typeof sourceLang === 'undefined' || sourceLang.includes(serviceLang)) && targetLang.includes(serviceLang);
```
or sth like this, not sure of the name `serviceLang`, but based on serviceAlias and languagesMapping names I guess it keeps some kind of language

2024-02-28 13:32 UTC, GrabowskiM commented on src/bundle/Resources/public/admin/js/ibexa-automated-translation.js
> +    sourceLabel?.addEventListener('click', toggleClass);
```suggestion
    form.addEventListener('click', () => error?.classList.add('invisible'), false);
    sourceLabel?.addEventListener('click', toggleClass, false);
```

2024-02-28 13:32 UTC, GrabowskiM commented on src/bundle/Resources/public/admin/js/ibexa-automated-translation.js
> +    });
I think there's something missing in here, as you iterate by `.ibexa-data-source__label.is-checked`, but inside you don't use anything from this iterable array?
I guess it was supposed to remove disabled from button if sth is checked, but in such case it should be enough:
```suggestion
    if (container.querySelector('.ibexa-data-source__label.is-checked')) {
        form.querySelector('.ibexa-btn--create-translation').removeAttribute('disabled');
    };
```

2024-02-28 13:32 UTC, GrabowskiM commented on src/bundle/Resources/public/admin/js/ibexa-automated-translation.js
> +    container.querySelectorAll('.ibexa-dropdown__source select option:checked').forEach(() => {
same as above

2024-02-28 13:32 UTC, GrabowskiM commented on src/bundle/Resources/public/admin/js/ibexa-automated-translation.js
> +    form.addEventListener('submnit', submitForm);
```suggestion
    form.addEventListener('submnit', submitForm, false);
```

2024-03-07 06:16 UTC, GrabowskiM approved these changes

2024-03-07 10:25 UTC, tischsoic approved these changes

2024-03-07 12:13 UTC, dew326 approved these changes

2024-03-12 10:57 UTC, konradoboza approved these changes

2024-03-18 14:22 UTC, ciastektk approved these changes

2024-03-18 14:34 UTC, dew326 approved these changes

2024-03-18 14:34 UTC, dew326 commented on src/bundle/Resources/public/admin/js/ibexa-automated-translation.js
> +
```suggestion
```

2024-03-18 14:34 UTC, dew326 commented on src/bundle/Resources/public/admin/js/ibexa-automated-translation.js
> +    if (baseLanguageSelect && translatorSelect) {
```suggestion

    if (baseLanguageSelect && translatorSelect) {
```

2024-03-18 14:34 UTC, dew326 commented on src/bundle/Resources/public/admin/js/ibexa-automated-translation.js
> +            if (translationSelectWrapper) {
```suggestion

            if (translationSelectWrapper) {
```

2024-03-18 14:34 UTC, dew326 commented on src/bundle/Resources/public/admin/js/ibexa-automated-translation.js
> +((doc) => {
```suggestion
((global, doc) => {
```
just for consistency.

2024-03-28 14:42 UTC, micszo commented
Please see: https://recordit.co/zAn4cm11Ux

When opening "Create a new translation" pop-up, after refreshing the page, select translation service dropdown is active with "No language" selected as source language. Which can lead to an error in the next step.

The same occurs when pop-up is opened for the first time for given content item (Dropdown is deactivated when "No language" is selected for the first time).

2024-03-29 13:44 UTC, micszo approved these changes
QA Approved on Ibexa Commerce 4.5.7-dev.

2024-03-29 13:58 UTC, merged